import type { SocialLink } from "@/lib/home-content";

/** Single source of truth for Hatz Court Builders contact & branding. */
export const BUSINESS = {
  nameShort: "Hatz Court Builders",
  nameFull: "Hatz Court Builders",
  tagline: "Custom Court Construction & Resurfacing",
  legalNote: "Idaho Public Works License #9471850",
  phoneTel: "tel:+12089290002",
  phoneDisplay: "(208) 929-0002",
  email: "info@hatzconstruction.com",
  emailMailto: "mailto:info@hatzconstruction.com",
  address: "Boise, Idaho; Scottsdale, Arizona",
  addressLines: ["Boise, Idaho", "Scottsdale, Arizona"] as const,
  mapsGoogleUrl: "https://maps.app.goo.gl/VPikhYpZuKDAp6A39",
  mapsGoogleUrlScottsdale: "https://maps.app.goo.gl/Aqcgk3WWS9B5BMpJ8",
  mapsAppleUrl: "https://maps.apple.com/?address=Boise,%20Idaho",
  website: "https://hatzcourtbuilders.com/",
  hoursShort: "Hours: 24/7",
  foundedYearLabel: "2024",
  foundedDate: "June 19, 2024",
  gbpCategory: "Tennis Court Construction Company",
  gbpCategories: [
    "Tennis Court Construction Company",
    "Contractor",
    "Basketball Court Contractor",
  ] as const,
  serviceAreaShort: "Boise, Scottsdale, and surrounding Idaho & Arizona communities",
  /** Primary Idaho service cities (used in copy and service area sections). */
  serviceCities: [
    "Boise",
    "Meridian",
    "Nampa",
    "Caldwell",
    "Middleton",
    "Star",
    "Eagle",
    "Kuna",
    "Fruitland",
    "Sun Valley",
    "Hailey",
    "Ketchum",
    "Stanley",
    "McCall",
    "Twin Falls",
    "Mountain Home",
    "Homedale",
  ] as const,
  serviceCitiesIdaho: [
    "Boise",
    "Meridian",
    "Nampa",
    "Caldwell",
    "Middleton",
    "Star",
    "Eagle",
    "Kuna",
    "Fruitland",
    "Sun Valley",
    "Hailey",
    "Ketchum",
    "Stanley",
    "McCall",
    "Twin Falls",
    "Mountain Home",
    "Homedale",
  ] as const,
  serviceCitiesArizona: [
    "Phoenix",
    "Scottsdale",
    "Fountain Hills",
    "Mesa",
    "Gilbert",
    "Chandler",
    "Glendale",
    "Tempe",
    "Peoria",
    "Arcadia",
    "Anthem",
  ] as const,
  serviceCountiesIdaho: [
    "Ada",
    "Canyon",
    "Boise",
    "Valley",
    "Custer",
    "Blaine",
    "Camas",
    "Twin Falls",
    "Owyhee",
    "Payette",
    "Gem",
    "Gooding",
  ] as const,
  serviceCountiesArizona: ["Maricopa"] as const,
  descriptionShort:
    "Hatz Court Builders is a trusted court builder serving Boise, Meridian, Nampa, Caldwell, Eagle, and nearby Idaho areas. We build custom tennis, basketball, pickleball, and multi-use courts with acrylic, modular, turf, asphalt, and concrete systems. We also handle resurfacing, repairs, striping, and full design-build projects.",
  description: `Hatz Court Builders is a trusted court builder serving Boise, Meridian, Nampa, Caldwell, Eagle, Kuna, Middleton, Star, Twin Falls, and nearby Idaho areas — plus Phoenix, Scottsdale, Mesa, Gilbert, Chandler, and surrounding Arizona communities. We specialize in custom court construction for residential and commercial projects, including tennis, basketball, pickleball, volleyball, futsal, bocce, padel, and multi-use courts. Our team installs all surface types, including acrylic, cushioned systems, modular surfaces, synthetic turf, asphalt, and concrete. We also provide court resurfacing, repairs, renovations, striping, custom logos, lighting, fencing, and full site preparation. From backyard courts to large multi-court facilities, we handle everything from design to completion.`,
  targetMarket:
    "Homeowners, parks & recreation departments, and schools — sports enthusiasts ages 30s–80s.",
  offers: ["Free Consultation", "10% Off Specials Available"] as const,
  primaryService: "Sports construction — pickleball acrylic courts, tennis, basketball, and full multi-court builds",
  services: [
    "Pickleball court construction",
    "Tennis court construction",
    "Basketball court construction",
    "Multi-use courts",
    "Volleyball courts",
    "Acrylic surfacing",
    "Cushioned acrylic systems",
    "Hardwood courts",
    "Modular tile courts",
    "Synthetic turf courts",
    "Court resurfacing",
    "Court repairs & renovations",
    "Line striping",
    "Custom logos",
    "Lighting & fencing",
    "Site preparation",
    "Design-build projects",
  ] as const,
  uniqueSellingPoints: [
    "All surface types — not just acrylic, hardwood, or modular like most competitors",
    "One-stop shop for surfacing, components, fencing, lighting, and design",
    "Cushioned acrylic and standard hardcourt acrylic options",
    "Residential and commercial court construction",
  ] as const,
  keywords: [
    "Court builder",
    "Pickleball court construction",
    "Basketball court construction",
    "Tennis court construction",
    "Court design",
  ] as const,
  mapEmbedSrc:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1476293.7556148497!2d-115.61409395!3d43.72330254999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4a7ee46ba4b331ad%3A0xf8a3188e7e80a9fa!2sHatz%20Court%20Builders!5e0!3m2!1sen!2sph!4v1781158453955!5m2!1sen!2sph",
  mapEmbedSrcScottsdale:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d425677.5265753157!2d-111.90041805000001!3d33.5376365!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4144c0a539909cfb%3A0x91abca52b94d82a8!2sHatz%20Court%20Builders!5e0!3m2!1sen!2sph!4v1781158489503!5m2!1sen!2sph",
  mapCenter: { lat: 43.615, lng: -116.2146 } as const,
  mapDefaultZoom: 10,
  logoSrc: "/images/logo/hatz-court-builders-logo.png?v=5",
  logoWidth: 952,
  logoHeight: 161,
  wordmarkSrc: "/images/logo/hatz-court-builders-logo.png?v=5",
  wordmarkWidth: 952,
  wordmarkHeight: 161,
} as const;

/** Canonical profiles & listings — footer, contact, and home content pull from here. */
export const DEFAULT_SOCIAL_LINKS: SocialLink[] = [
  { label: "Google Business", href: BUSINESS.mapsGoogleUrl },
  {
    label: "Facebook",
    href: "https://www.facebook.com/people/Hatz-Sports-Construction/61582408076754/",
  },
  {
    label: "Instagram",
    href: "https://www.instagram.com/hatz_sports_construction",
  },
];

/** Homepage link label in “Other Services” sidebars on service landings. */
export const HOMEPAGE_SIDEBAR_LABEL = "Court Construction Boise";

/** Hostnames treated as “this site” when normalizing markdown links. */
export const SITE_INTERNAL_HOSTNAMES = ["hatzcourtbuilders.com", "www.hatzcourtbuilders.com"] as const;
