/** Auto-generated by scripts/import-gpm-blog-articles.mjs */
import type { BlogPost } from "@/lib/blog-types";

type FallbackDef = Omit<BlogPost, "bodyMarkdown"> & {
  mdFile: string;
  tocItems: NonNullable<BlogPost["tocItems"]>;
};

/** Imported GPM posts removed after site trim; only local fallbacks in blog-fallback.ts remain. */
export const GPM_IMPORTED_BLOG_FALLBACK_DEFS: FallbackDef[] = [];
