/** Auto-generated by scripts/rename-and-process-gallery-photos.mjs — do not edit by hand. */
export const HCB_SEO_FILENAME_SUFFIX = "Hatz Court Builders" as const;

export const HCB_GALLERY_IMAGE_PATHS = [
  "/images/hcb/aerial-backyard-multi-sport-modular-tile-court-construction-blue-gray-residential-hatz-court-builders.jpg",
  "/images/hcb/aerial-backyard-pickleball-basketball-court-construction-mountain-residential-hatz-court-builders.jpg",
  "/images/hcb/aerial-commercial-pickleball-court-construction-six-court-blue-green-lighting-facility-hatz-court-builders.jpg",
  "/images/hcb/aerial-commercial-pickleball-court-construction-six-court-blue-tan-acrylic-facility-hatz-court-builders.jpg",
  "/images/hcb/aerial-four-court-tennis-facility-outdoor-park-installation-lighting-hatz-court-builders.jpg",
  "/images/hcb/aerial-luxury-residential-blue-pickleball-court-construction-golf-course-property-hatz-court-builders.jpg",
  "/images/hcb/backyard-gray-basketball-court-installation-modular-tile-outdoor-hatz-court-builders.jpg",
  "/images/hcb/backyard-modular-tile-sport-court-custom-logo-installation-hatz-court-builders.jpg",
  "/images/hcb/backyard-multi-sport-pickleball-basketball-court-construction-hatz-court-builders.jpg",
  "/images/hcb/backyard-multi-sport-pickleball-basketball-court-construction-lighting-residential-hatz-court-builders.jpg",
  "/images/hcb/backyard-pickleball-basketball-court-blue-surfacing-multi-use-hatz-court-builders.jpg",
  "/images/hcb/backyard-pickleball-basketball-dual-sport-court-construction-hatz-court-builders.jpg",
  "/images/hcb/backyard-pickleball-court-construction-blue-gray-acrylic-residential-hatz-court-builders.jpg",
  "/images/hcb/backyard-pickleball-court-light-surface-finish-acrylic-installation-hatz-court-builders.jpg",
  "/images/hcb/basketball-tile-court-custom-logo-branding-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/basketball-tile-court-modular-hoop-goal-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/blue-and-orange-outdoor-pickleball-court-construction-apartment-amenity-acrylic-surfacing-hatz-court-builders.jpg",
  "/images/hcb/custom-blue-backyard-basketball-half-court-installation-glass-backboard-outdoor-surfacing-hatz-court-builders.jpg",
  "/images/hcb/double-outdoor-pickleball-court-construction-blue-green-acrylic-surfacing-fencing-hatz-court-builders.jpg",
  "/images/hcb/double-pickleball-court-blue-green-surface-acrylic-construction-hatz-court-builders.jpg",
  "/images/hcb/gray-pickleball-basketball-court-backyard-dual-sport-construction-hatz-court-builders.jpg",
  "/images/hcb/indoor-acrylic-basketball-pickleball-court-glass-garage-door-residential-hatz-court-builders.jpg",
  "/images/hcb/indoor-batting-cage-turf-installation-athletic-facility-hatz-court-builders.jpg",
  "/images/hcb/indoor-hardwood-basketball-court-construction-with-wall-mount-hoop-residential-gym-hatz-court-builders.jpg",
  "/images/hcb/indoor-hardwood-basketball-court-hoops-gym-interior-volleyball-multi-sport-hatz-court-builders.jpg",
  "/images/hcb/indoor-hardwood-basketball-court-wall-hoop-mount-residential-gym-hatz-court-builders.jpg",
  "/images/hcb/indoor-hardwood-pickleball-basketball-court-interior-multi-sport-hatz-court-builders.jpg",
  "/images/hcb/indoor-hardwood-sport-court-installation-basketball-flooring-construction-hatz-court-builders.jpg",
  "/images/hcb/line-paint-pickleball-basketball-on-concrete-dual-court-markings-hatz-court-builders.jpg",
  "/images/hcb/modular-court-tile-custom-logo-branding-outdoor-sport-court-hatz-court-builders.jpg",
  "/images/hcb/multi-sport-outdoor-backyard-court-construction-residential-hatz-court-builders.jpg",
  "/images/hcb/multicourt-modular-tile-backyard-installation-sport-court-hatz-court-builders.jpg",
  "/images/hcb/outdoor-green-basketball-court-construction-professional-surfacing-and-led-lighting-hatz-court-builders.jpg",
  "/images/hcb/outdoor-multi-court-acrylic-surfacing-pickleball-basketball-tennis-hatz-court-builders.jpg",
  "/images/hcb/outdoor-multi-court-pickleball-basketball-construction-green-blue-acrylic-surfacing-hatz-court-builders.jpg",
  "/images/hcb/outdoor-multi-court-pickleball-basketball-tennis-acrylic-construction-hatz-court-builders.jpg",
  "/images/hcb/outdoor-multi-court-tennis-pickleball-blue-tan-acrylic-surfacing-residential-installation-hatz-court-builders.jpg",
  "/images/hcb/outdoor-pickleball-court-construction-blue-orange-acrylic-surfacing-rural-residential-hatz-court-builders.jpg",
  "/images/hcb/outdoor-pickleball-court-construction-green-acrylic-mountain-residential-installation-hatz-court-builders.jpg",
  "/images/hcb/outdoor-pickleball-court-red-and-green-surface-acrylic-installation-hatz-court-builders.jpg",
  "/images/hcb/pickleball-basketball-line-paint-on-concrete-dual-sport-court-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-backyard-blue-gray-acrylic-surfacing-residential-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-backyard-modular-tile-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-green-and-red-surface-acrylic-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-green-blue-backyard-acrylic-construction-residential-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-hoa-community-blue-gray-acrylic-surfacing-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-hoa-line-paint-and-coating-acrylic-resurfacing-hatz-court-builders.jpg",
  "/images/hcb/pickleball-court-modular-tile-surfacing-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/pickleball-line-striping-on-concrete-court-construction-hatz-court-builders.jpg",
  "/images/hcb/pickleball-post-tension-concrete-commercial-court-construction-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-crack-repair-resurfacing-acrylic-renovation-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-pickleball-conversion-community-multi-court-resurfacing-green-maroon-acrylic-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-repair-school-facility-outdoor-resurfacing-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-resurface-and-repair-outdoor-acrylic-facility-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-resurface-blue-and-green-acrylic-outdoor-installation-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-resurface-crack-repair-acrylic-renovation-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-side-by-side-before-after-repair-resurfacing-hatz-court-builders.jpg",
  "/images/hcb/tennis-court-surface-cracks-and-wear-before-resurfacing-assessment-hatz-court-builders.jpg",
  "/images/hcb/tile-shuffleboard-court-installation-modular-outdoor-recreational-hatz-court-builders.jpg",
] as const;

export type HcbGalleryImagePath = (typeof HCB_GALLERY_IMAGE_PATHS)[number];

export function hcbImageAlt(imagePath: string): string {
  const filename = imagePath.split("/").pop() ?? "";
  const stem = filename.replace(/\.(webp|jpe?g|png)$/i, "");
  const suf = `-${slugifySuffix(HCB_SEO_FILENAME_SUFFIX)}`;
  const i = stem.endsWith(suf) ? stem.length - suf.length : -1;
  const kw = i === -1 ? stem : stem.slice(0, i);
  return kw.replace(/-/g, " ").trim();
}

function slugifySuffix(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
