/** Auto-generated by scripts/process-hcb-photos.mjs — do not edit by hand. */
export const HCB_SEO_FILENAME_SUFFIX = "Boise ID - Hatz Court Builders" as const;

export const HCB_GALLERY_IMAGE_PATHS = [
  "/images/hcb/backyard-gray-basketball-court-installation-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-modular-tile-sport-court-custom-logo-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-multi-sport-pickleball-basketball-court-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-pickleball-basketball-court-blue-surfacing-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-pickleball-basketball-dual-sport-court-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-pickleball-court-blue-gray-surface-finish-boise-id-hatz-court-builders.webp",
  "/images/hcb/backyard-pickleball-court-light-surface-finish-boise-id-hatz-court-builders.webp",
  "/images/hcb/basketball-tile-court-custom-logo-branding-boise-id-hatz-court-builders.webp",
  "/images/hcb/basketball-tile-court-modular-hoop-goal-boise-id-hatz-court-builders.webp",
  "/images/hcb/double-pickleball-court-blue-green-surface-boise-id-hatz-court-builders.webp",
  "/images/hcb/gray-pickleball-basketball-court-backyard-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-acrylic-basketball-pickleball-court-glass-garage-door-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-acrylic-basketball-pickleball-court-wall-hoop-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-batting-cage-turf-installation-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-basketball-court-hoops-gym-flooring-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-basketball-court-hoops-gym-interior-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-basketball-court-wall-hoop-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-court-wall-mount-hoop-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-pickleball-basketball-court-interior-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-pickleball-basketball-multi-sport-court-boise-id-hatz-court-builders.webp",
  "/images/hcb/indoor-hardwood-sport-court-installation-boise-id-hatz-court-builders.webp",
  "/images/hcb/line-paint-pickleball-basketball-on-concrete-boise-id-hatz-court-builders.webp",
  "/images/hcb/modular-court-tile-custom-logo-branding-boise-id-hatz-court-builders.webp",
  "/images/hcb/multi-sport-outdoor-backyard-court-boise-id-hatz-court-builders.webp",
  "/images/hcb/multicourt-modular-tile-backyard-installation-boise-id-hatz-court-builders.webp",
  "/images/hcb/outdoor-multi-court-acrylic-surfacing-boise-id-hatz-court-builders.webp",
  "/images/hcb/outdoor-multi-court-pickleball-basketball-tennis-boise-id-hatz-court-builders.webp",
  "/images/hcb/outdoor-pickleball-court-red-and-green-surface-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-basketball-line-striping-on-concrete-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-backyard-blue-gray-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-backyard-modular-tile-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-green-and-red-surface-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-green-blue-backyard-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-hoa-community-blue-gray-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-hoa-line-paint-and-coating-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-court-modular-tile-surfacing-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-line-striping-on-concrete-boise-id-hatz-court-builders.webp",
  "/images/hcb/pickleball-post-tension-concrete-commercial-court-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-before-cracks-damage-assessment-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-crack-repair-resurfacing-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-repair-school-facility-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-resurface-and-repair-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-resurface-blue-and-green-acrylic-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-resurface-crack-repair-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-side-by-side-before-after-repair-boise-id-hatz-court-builders.webp",
  "/images/hcb/tennis-court-surface-cracks-and-wear-boise-id-hatz-court-builders.webp",
  "/images/hcb/tile-shuffleboard-court-installation-boise-id-hatz-court-builders.webp",
] as const;

export type HcbGalleryImagePath = (typeof HCB_GALLERY_IMAGE_PATHS)[number];

export function hcbImageAlt(imagePath: string): string {
  const filename = imagePath.split("/").pop() ?? "";
  const stem = filename.replace(/\.webp$/i, "");
  const suf = `-${slugifySuffix(HCB_SEO_FILENAME_SUFFIX)}`;
  const i = stem.endsWith(suf) ? stem.length - suf.length : -1;
  const kw = i === -1 ? stem : stem.slice(0, i);
  return kw.replace(/-/g, " ").trim();
}

function slugifySuffix(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
